language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install -y collectd collectd-core

python:
  - 2.6
  - 2.7
  - 3.3

install:
  # workaround for travis build vm's and multiprocessing
  # see https://github.com/travis-ci/travis-core/issues/187
  - sudo rmdir /dev/shm
  - sudo ln -Tsf /{run,dev}/shm
  # install dependencies
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage>=3.6 nose>=1.3.0 flake8>=2.1 coveralls>=0.3 --use-mirrors
  # install bucky2
  - pip install -e . --use-mirrors

script:
  - flake8 --show-source --ignore=E501,W391 .
  - nosetests -v --with-coverage

after_success:
  - coveralls

